const DEFAULT_TIMEOUT = 12000;
const GOOGLE_ACCOUNT = 'kmsrunners'
const GOOGLE_PASSWORD = 'KMSRunners@2020'
const STRAVA_ACCOUNT = 'kmsrunners@gmail.com'
const STRAVA_PASSWORD = 'KMSRunners@2020'

module.exports = {
  DEFAULT_TIMEOUT,
  GOOGLE_ACCOUNT,
  GOOGLE_PASSWORD,
  STRAVA_ACCOUNT,
  STRAVA_PASSWORD
};